### ISSUE TITLE
Update write_excalibur_buffer to add header onto frames

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#12]
FileWriter previously didn't account for the header and write_excalibur_buffer was written to match this. Now that @timcnicholls has updated FileWriter to account for the buffer, testing with write_excalibur_buffer doesn't work (writes the same frame repeatedly).

**Comment by timcnicholls** [comment]
This issue is now obsolete as we have PCAP playback mechanisms for testing the odin-data chain
