### ISSUE TITLE
Add generic metadata writer

### ISSUE THREAD

**Issue by timcnicholls** [odin-detector/odin-data#138]
Placeholder issue for PR @MattTaylorDLS intending to get in prior to 0.7.0 release

**Comment by ulrikpedersen** [comment]
Is there a PR in the works for this one, @MattTaylorDLS? Seems like one of the last remaining items before we can roll the 0.7 release...

**Comment by ulrikpedersen** [comment]
Ah, apologies, there is a merged PR that was also tagged with this issue. I didn't spot that at first glance... Looks like we can close this one?

**Comment by MattTaylorDLS** [comment]
Yep this is in
