### ISSUE TITLE
Verify behaviour of bad configuration messages.

### ISSUE THREAD

**Issue by ajgdls** [odin-detector/odin-data#173]
We need to check that sending a bad configuration message does not terminate the FrameProcessor application.  Instead it should send a failure response IPC message.

**Comment by GDYendell** [comment]
The current behaviour is that any configuration messages that throw a runtime_error will be caught in `FrameProcessorController::handleCtrlChannel` and the error will be both logged and passed back on the ctrl channel with a nack.

The behaviour I was seeing is where the JSON file loaded at startup causes an error. We agreed in this case the best thing to do is abort with an error message, so this is a non-issue.
