### ISSUE TITLE
Processes throw generic exception if an incorrectly formatted JSON config file is specified

### ISSUE THREAD

**Issue by timcnicholls** [odin-detector/odin-data#186]
Currently, both the frameReceiver and the frameProcessor throw an unhelpful exception error message and terminate if started with a JSON config file that contains syntax errors:
```
ERROR FR.App null - Generic exception during frame receiver run: rapidjson assertion thrown
```
```
ERROR FP.App null - Caught unhandled exception in FrameProcessor, application will terminate: rapidjson assertion thrown
```
This can be resolved by changing the calls to `param_doc.Parse()` in the relevant app startups to something akin to:
```
if (param_doc.Parse(json.c_str()).HasParseError())
{
   std::stringstream msg;
   msg << "Parsing JSON configuration failed at offset " 
     << param_doc.GetErrorOffset() << ": " 
     << rapidjson::GetParseError_En(param_doc.GetParseError());
   throw OdinData::OdinDataException(msg.str());
}
```
There's a wider discussion about whether the app should terminate at this point or report and error and remain responsive to interrogation by a controlling client. Either way, the exception reporting can be improved.

**Comment by ajgdls** [comment]
@timcnicholls that will be a huge improvement, especially if the error message really explains what the problem with the JSON file is!
I've spent a *lot* of time looking for problems only to find out I have an extra (or missing) comma in the JSON configuration file.

**Comment by timcnicholls** [comment]
Yeah @ajgdls that's exactly what burnt me too. The byte offset is a start but hard to translate into e.g. a line number. Given that the parser takes the entire file as a string, I was wondering about also printing out e.g +/- x characters either side of the offset.

**Comment by GDYendell** [comment]
Could it search for +/- x `\n`s either side of the offset?

**Comment by timcnicholls** [comment]
That's a good idea @GDYendell, I don't see why not.
