### ISSUE TITLE
Consider rationalising configuration mechanisms for odin-data apps

### ISSUE THREAD

**Issue by timcnicholls** [odin-detector/odin-data#187]
Currently we have four methods of configuring the frameReceiver and frameProcessor:
1. Command line arguments
2. INI-style configuration files
3. JSON configuration files
4. JSON configuration messages sent over the control channel

None of these are capable of completely configuring the application, for instance:
- the logging configuration can only be specified at the command line or INI file
- the command line and INI file are not capable of expressing the imperative syntax needed to send successive configuration 'commands' to the FP to construct a plugin chain
- rebinding control IpcChannel endpoints is handled inconsistently across the default value, INI config file and JSON configuration, leading to binding errors at startup in the FR.

**Proposal for discussion**: drop the INI config files completely, leaving command-line arguments JSON config file and messages.

**Comment by ajgdls** [comment]
I would also propose that maybe we cut down the number of command line options, keeping only the ones that really are necessary (ctrl channel, log config etc)?
