### ISSUE TITLE
Do we still use the old client python code?

### ISSUE THREAD

**Issue by ajgdls** [odin-detector/odin-data#189]
There are some old client python files in odin-data.  This is forcing odin-data to depend on npyscreen.  I notice in at least one file there is a hardcoded path to my DLS home directory to load a percival library.

I'm guessing no-one ever uses any of this now and so I think we should clean it up and remove these kind of dependencies.

**Comment by MattTaylorDLS** [comment]
I dont use them

**Comment by timcnicholls** [comment]
Agreed, we should have a good spring clean of that entire package.

**Comment by ajgdls** [comment]
Directory tools/python/odin_data/frame_processor

I think we should eliminate the whole directory.  There is a file frame_processor.py that is a test harness for a FrameProcessor application but I'm not sure we need that any more as we have the real frame processor application with the dummy plugin?

**Comment by GDYendell** [comment]
Fixed by #191
