### ISSUE TITLE
Obtuse Error Message when a frame with an unexpected dataset name is received

### ISSUE THREAD

**Issue by ANeaves** [odin-detector/odin-data#213]
If the FileWriterPlugin receives a frame that has a dataset name that isn't one of the ones it's been configured to receive, the error message produced comes from Acquisition.cpp, and looks like the following:
`FP.Acquisition ERROR - Out of Range exception: map::at`
which stops the frame from being saved to a file, but is not very clear what the reason is. I had to dig into the Acquisition code to find out that it was the dataset name issue causing the error.

**Comment by ajgdls** [comment]
See PR #241
