### ISSUE TITLE
Linker error when relying on FindHDF5

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#246]
Quote from the person who had the issue:

>  Linker error when building offsite. Had to rename a cmake variable:  HDF5HL_LIBRARIES -> HDF5_HL_LIBRARIES.
HDF5_HL_LIBRARIES is what FindHDF5.cmake returns and the script uses it when not working with /dls_sw/tools. The custom script for tools was using HDF5HL_LIBRARIES. Renaming means the same variable names are used in both cases and passed on to the rest of the build.

This isn't a problem at DLS because we don't use FindHDF5. @timcnicholls is this something you have had to work around, or do you not use FindHDF5 either?

**Comment by timcnicholls** [comment]
> This isn't a problem at DLS because we don't use FindHDF5. @timcnicholls is this something you have had to work around, or do you not use FindHDF5 either?

I always explicitly set `-DHDF5_ROOT` in the cmake command.
