### ISSUE TITLE
Make it possible for the LiveViewPlugin to publish the Nth frame of every configured dataset

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#333]
Currently it is possible to configure a list of datasets to publish, but there is only a single counter used for the throttling logic to decide whether to publish a frame.

It could map that list of datasets to a list of counters specific to each dataset, so that it is possible to send the Nth frame of every configured dataset and not just the one that happens to make the single counter hit the magic number.

**Comment by timcnicholls** [comment]
@ANeaves was the original author of this plugin and she's happy to look at implementing this change.

**Comment by ANeaves** [comment]
hey @GDYendell , I've pushed a branch and opened a PR to address this. Currently, it assumes the same downsample rate for each dataset. Is this sufficient, or are you imagining the ability to declare different downsample rates for different datasets?

**Comment by GDYendell** [comment]
Hi @ANeaves! I think the same rate is for all fine. The main thing is that all the datasets get published when the counter hits the magic number, rather than just one of them as it is now.
