### ISSUE TITLE
Implement ParameterTree for FR adapter

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#346]

**Comment by GDYendell** [comment]
This should just work with the new generic OdinDataAdapter. Check this.

**Comment by GDYendell** [comment]
@jsouter did you do this while working on https://github.com/DiamondLightSource/fastcs-odin/pull/33?

**Comment by GDYendell** [comment]
That is pretty much all I did for the meta writer so that may be all that is required.

**Comment by jsouter** [comment]
Here is the diff of a branch I made that makes OdinDataController generic, and makes subclasses for FrameProcessorController and FrameReceiverController (which is actually an alias for the base OdinDataController), and FrameReceiver(/Processor)Adapter classes that use these controllers. 

This would mean we could still use the existing odin_server.cfg's module paths without having to specify a frame_processor flag. 
If we'd rather keep fastcs-dev as it is, I can make a PR to just delete frame_receiver_adapter.py as OdinDataAdapter makes it redundant.

https://github.com/odin-detector/odin-data/compare/fastcs-dev...jsouter:odin-data:controllers

**Comment by GDYendell** [comment]
I think I would like to see that diff as PR to fastcs-dev for discussion.

Do we understand why the fr check is commented out, currently? @ajgdls?

**Comment by jsouter** [comment]
Okay, PR here https://github.com/odin-detector/odin-data/pull/362/files

**Comment by ajgdls** [comment]
The check was not implemented during development of the new version of the class.  What is commented out there is a stub which needs an implementation to check on availability of buffers from the FR.

**Comment by ajgdls** [comment]
Oh sorry, for some context... In the previous version of the frame processor adapter, the FP adapter would connect to and check the number of free buffers according to the FR adapter.  It would test this against a defined threshold and refuse to send the command to start writing if the check failed.
The idea was to give prior warning if the system was being starved of buffers rather than allowing it to start and then potentially fail quickly.

**Comment by GDYendell** [comment]
Completed in #362. Added #364 for further work.
