### ISSUE TITLE
Expose commands within the frameProcessor

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#352]
To support e.g. start writing, stop writing in the hdf plugin. We would add a new `IpcMsgVal` for commands (`MsgValCmdCommand`), add `command` and `request_commands` methods to `FrameProcessorController` / `FrameProcessorPlugin` and then it should just be sent to the correct plugin based on the first part of the path (e.g. "hdf") and then only that plugin should have to handle the command subsystem.

`request_commands` should return a dictionary of command name to what parameters it takes, or None / empty dict if it does not take any parameters.
`command` should take a command name and a dict of parameters (again empty / not given if it does not take parameters)

**Comment by ajgdls** [comment]
See PR 

https://github.com/odin-detector/odin-data/pull/359
