### ISSUE TITLE
Add start and stop commands to FileWriterPlugin

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#357]
- [x] Depends on #359 

- Implement `"start_writing"` and `"stop_writing"` in `execute` to replace `hdf/config/write`
- Return `["start_writing", "stop_writing"]` in `requestCommands`

---

To be tested alongside
- [ ] https://github.com/odin-detector/odin-data/issues/363
- [ ] https://github.com/DiamondLightSource/fastcs-odin/issues/41

**Comment by jsouter** [comment]
Commenting so I can be assigned!
