### ISSUE TITLE
Re-implement decoder config caching in new FrameReceiverAdapter

### ISSUE THREAD

**Issue by GDYendell** [odin-detector/odin-data#364]
This was lost here: https://github.com/odin-detector/odin-data/pull/362#issuecomment-2411651234

**Comment by jsouter** [comment]
Looking at this again I believe this is already implemented by `process_config_changes` in the base `OdinDataController` - the FRs do get re-instantiated when I change a Decoder Config param like Udp Packets Per Frame via FastCS, though not when changing Enable Packet Logging

**Comment by jsouter** [comment]
Good, I realised the reason why it didn't work for enable packet logging was because of the issue I was explaining yesterday of FastCS sending it as an int instead of a bool and odin rejecting it
