### ISSUE TITLE
mpirun script and instructions

### ISSUE THREAD

**Issue by timcnicholls** [odin-detector/odin-data#9]
_From @ulrikpedersen on February 5, 2016 10:34_

Add installation instructions for mpirun and a script/configuration to start multiple instances of both frameReceiver and filewriter across multiple machines.

Currently this has to be done manually.

_Copied from original issue: percival-detector/framereceiver#40_

**Comment by timcnicholls** [comment]
Is this still useful @ulrikpedersen ??

**Comment by ulrikpedersen** [comment]
Hmmm... yes, maybe no... It certainly isn't a priority - and we have our own service infrastructure at DLS so won't need it for production.

For testing and development it might be useful as you could start up a whole system with multiple processes across multiple hosts with a single command. However, stdout/stderr will appear in the single terminal window and individual processes cannot be restarted without restarting the whole lot together... Would this be useful to developers? @MattTaylorDLS @ajgdls @MattTaylorDLS @timcnicholls ?

**Comment by timcnicholls** [comment]
@ulrikpedersen I've typically found other ways to launch an ensemble of processes when testing here, so probably wouldn't use it myself.

**Comment by MattTaylorDLS** [comment]
Yes, likewise

**Comment by ulrikpedersen** [comment]
OK, lets abandon this idea :+1:
